# TASK 1 - SQRT2

October 5th, 2020: Write a Python function called sqrt2 that calculates and prints to the screen the square root of 2 to 100 decimal places. Your code should not depend on any module from the standard library1 or otherwise. You should research the task first and include references and a description of your algorithm.

In [1]:
def sqrt2(my_number): 
    # I researched how to do a nested function to encapsulate sqrt2 as the overarching function, outer / inner function 
    # see https://stackabuse.com/python-nested-functions/
    # my_number is 2, when the function sqrt2 is called sqrt2(2), see last line of code below


    x = my_number * 100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
    # Because Python does not do 100 decimal places, we multiply 2 to a really large integer, where the square root of this number will be an integer length of 101 characters
    # e.g. 14142135623730950488016887242096980785696718753769480731766797379907324784621070388503875343276415727
    # is square root of 200000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
    # The above could also be coded this way x = my_number * 10 ** 200
 
    r = x

    def test_diffs(x, r): 

        # test_diffs is the inner function of sqrt2, the code which I used for this inner function was given to me by expert on stackoverflow
        # https://stackoverflow.com/questions/64278117/is-there-a-way-to-create-more-decimal-points-on-python-without-importing-a-libra/64278569?noredirect=1#comment113668731_64278569
        # on my question on stackoverflow I describe the research I have done, and how far I got with a possible solution
        
        
        d0 = abs(x - r**2)
        dm = abs(x - (r-1)**2)
        dp = abs(x - (r+1)**2)
        minimised = d0 <= dm and d0 <= dp
        below_min = dp < dm
        return minimised, below_min

    while True:
        oldr = r # this is a variable used for keeping track of original numaber
        r = (r + x // r) // 2

        minimised, below_min = test_diffs(x, r)
        if minimised:
            break

        if r == oldr:
            if below_min:
                r += 1 # increment r by 1
            else:
                r -= 1 # decrease r by 1
            minimised, _ = test_diffs(x, r)

            if minimised:
                break

    # We could present answer using print formatting from original stackoverflow answer
    # https://stackoverflow.com/questions/64278117/is-there-a-way-to-create-more-decimal-points-on-python-without-importing-a-libra/64278569?noredirect=1#comment113668731_64278569
    # print(f'{r // 10**100}.{r % 10**100:0100d}')"""

    # Or we can code to convert the final number into a string, and separate the string into two parts and add a fullstop in the middle https://stackoverflow.com/questions/1228299/changing-one-character-in-a-string
    r = str(r)
    text = r[:1] + "." + r[1:]
    print(text)


sqrt2(2) # call the function sqrt

1.4142135623730950488016887242096980785696718753769480731766797379907324784621070388503875343276415727



## My Notes for trying to show Sqrt2 to 100 decimal places

My answer above heavily depended on help from a stackoverflow user, my research into this question prior to using stackoverflow can be found below

Last Semester we worked on Newton's method of finding square roots

[https://github.com/g00387822/pands-problem-sheet/blob/master/5-squareroot.py](https://github.com/g00387822/pands-problem-sheet/blob/master/5-squareroot.py)

I tried to reuse the code from last Semester to find the Square Root of 2 (Various .py draft files can be found in Rough_draft_work_sqrt2)

Unfortunately Python has its limitations on the amount of Decimal places that it will show [read more](https://docs.python.org/3.4/tutorial/floatingpoint.html)

After much research and frustration, I consolidated what I had learned and drafted in code

, and asked the question on StackOverFlow

### Is there a way to create more decimal points on Python without importing a library/module?

[Is there a way to create more decimal points on Python without importing a library/module?](https://stackoverflow.com/questions/64278117/is-there-a-way-to-create-more-decimal-points-on-python-without-importing-a-libra)

On Stackoverflow I received this solution to be able to complete the task



x = 2 * 10 ** 200

r = x

def test_diffs(x, r):
    d0 = abs(x - r**2)
    dm = abs(x - (r-1)**2)
    dp = abs(x - (r+1)**2)
    minimised = d0 <= dm and d0 <= dp
    below_min = dp < dm
    return minimised, below_min

while True:
    oldr = r
    r = (r + x // r) // 2

    minimised, below_min = test_diffs(x, r)
    if minimised:
        break

    if r == oldr:
        if below_min:
            r += 1
        else:
            r -= 1
        minimised, _ = test_diffs(x, r)
        if minimised:
            break

print(f'{r // 10**100}.{r % 10**100:0100d}')

Gives:

1.4142135623730950488016887242096980785696718753769480731766797379907324784621070388503875343276415727


Compare with my solution below


def sqrt2(my_number): # I researched how to do a nested function to encapsulate sqrt2 as the overarching function, outer / inner function see https://stackabuse.com/python-nested-functions/
                      # my_number is 2, when the function sqrt2 is called sqrt2(2), see last line of code below


    x = my_number * 100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
    # Because Python does not do 100 decimal places, we multiply 2 to a really large integer, where the square root of this number will be an integer length of 101 characters
    # e.g. 14142135623730950488016887242096980785696718753769480731766797379907324784621070388503875343276415727
    # is square root of 200000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
    # The above could also be coded this way x = my_number * 10 ** 200
 
    r = x

    def test_diffs(x, r): 

        # test_diffs is the inner function of sqrt2, the code which I used for this inner function was given to me by expert on stackoverflow
        # https://stackoverflow.com/questions/64278117/is-there-a-way-to-create-more-decimal-points-on-python-without-importing-a-libra/64278569?noredirect=1#comment113668731_64278569
        # on my question on stackoverflow I describe the research I have done, and how far I got with a possible solution
        
        
        d0 = abs(x - r**2)
        dm = abs(x - (r-1)**2)
        dp = abs(x - (r+1)**2)
        minimised = d0 <= dm and d0 <= dp
        below_min = dp < dm
        return minimised, below_min

    while True:
        oldr = r # this is a variable used for keeping track of original numaber
        r = (r + x // r) // 2

        minimised, below_min = test_diffs(x, r)
        if minimised:
            break

        if r == oldr:
            if below_min:
                r += 1 # increment r by 1
            else:
                r -= 1 # decrease r by 1
            minimised, _ = test_diffs(x, r)

            if minimised:
                break

    # We could present answer using print formatting from original stackoverflow answer
    # https://stackoverflow.com/questions/64278117/is-there-a-way-to-create-more-decimal-points-on-python-without-importing-a-libra/64278569?noredirect=1#comment113668731_64278569
    # print(f'{r // 10**100}.{r % 10**100:0100d}')"""

    # Or we can code to convert the final number into a string, and separate the string into two parts and add a fullstop in the middle https://stackoverflow.com/questions/1228299/changing-one-character-in-a-string
    r = str(r)
    text = r[:1] + "." + r[1:]
    print(text)




sqrt2(2) # call the function sqrt


I have provided references to the code of others, and have worked towards consolidating the code into one function sqrt2


The Square Root of Two to 1 Million Digits can be found on this link
[https://apod.nasa.gov/htmltest/gifcity/sqrt2.1mil](https://apod.nasa.gov/htmltest/gifcity/sqrt2.1mil)


The typical way of solving this question on Python 3 would be to do this

>>> import decimal
>>> decimal.getcontext().prec=101
>>> Decimal("2").sqrt()
Decimal('1.4142135623730950488016887242096980785696718753769480731766797379907324784621070388503875343276415727')

# Task 2 - CHI-SQUARED

November 2nd, 2020: The Chi-squared test for independence is a statistical hypothesis test like a t-test. It is used to analyse whether two categorical variables are independent. The Wikipedia article gives the table below as an example [4], stating the Chi-squared value based on it is approximately 24.6. Use scipy.stats to verify this value and calculate the associated p value. You should include a short note with references justifying your analysis in a markdown cell. https://en.wikipedia.org/wiki/Chi-squared_test

![table.png](table.png)

### Videos Watched

https://youtu.be/fMIwIKLGke0
associated Jupyter Notebook https://nbviewer.jupyter.org/github/bhattbhavesh91/chi-squared-feature-selection-selectkbest/blob/master/chi-squared-selectkbest-notebook.ipynb

This referenced use of 

import pandas as pd
import numpy as np
from scipy import stats
from sklearn.feature_selection import SelectKBest, chi2


https://youtu.be/WXPBoFDqNVk <br>
https://youtu.be/Pbo7VbHK9cY <br>
https://youtu.be/I10q6fjPxJ0 <br>

At layman entry point into statistics, for me it was at first a daunting task to find for dummies statistical training guides on chi-squared test, and to apply that to the scipy.stats functions available.

### Written Sources of investigation

As the task assignment specifically referenced scipy.stats I checked Stackoverflow

https://stackoverflow.com/questions/44817281/performing-chi-squared-test-in-python

from scipy.stats import chisquare  
chisquare([ <your data points>])

I also checked the user manual.
    
https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.chisquare.html

I raised a question on Stackoverflow hoping that with expert advice, I could both broaden my understanding of the chi square test, and to use the best available scipy.stats function to reference the table data.
    
My question can be found here:
https://stackoverflow.com/questions/64669448/understanding-scipy-stats-chisquare
    
### My Question On Stackoverflow
    
Can someone help me with scipy.stats.chisquare? I do not have a statistical / mathematical background, and I am learning scipy.stats.chisquare with this data set from https://en.wikipedia.org/wiki/Chi-squared_test

The Wikipedia article gives the table below as an example, stating the Chi-squared value based on it is approximately 24.6. I am to use scipy.stats to verify this value and calculate the associated p value.

![table.png](table.png)
    
I have found what looks like the most likely formula solutions to help me here

https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.chisquare.html

![chi_squared_solutions.png](chi_squared_solutions.png)  

As I am new to statistics, and also the use of scipy.stats.chisquare I am just not sure of the best approach, and how best to enter the data from provided table into the arrays, and whether to supply expected values? from Wikipedia.
    


### Final Solution from Stackoverflow

![table.png](table.png)


>> That data is a contingency table. SciPy has the function scipy.stats.chi2_contingency that applies the chi-square test to a contingency table. It is fundamentally just a reqular chi-square test, but when applied to a contingency table, the expected frequencies are calculated under the assumption of independence (chi2_contingency does this for you), and the degrees of freedom depends on the number of rows and columns (chi2_contingency calculates this for you, too).
>> Here's how you can apply the chi-square test to that table:
>> https://stackoverflow.com/questions/64669448/understanding-scipy-stats-chisquare/

From using the above answer, I didn't need to research further the expected frequencies for each category, because the chi2_contingency does this for you.
The chi2_contingency function also calulates the degrees of freedom.

As requested for this task, this chi2_contingency function was able to verify the value of 24.6 (24.571) and calculate the associated p value as 0.00040984

In [2]:
import numpy as np
from scipy.stats import chi2_contingency


# We use a multi dimensional data array from numpy to represent the table

table = np.array([[90, 60, 104, 95], # White collar
                  [30, 50,  51, 20], # Blue collar
                  [30, 40,  45, 35]]) # No collar

# the variables chi2, p, dof, expected

chi2, p, dof, expected = chi2_contingency(table) #chi2_contingency function from scipy.stats is applied to the table
    # the variables chi2, p, dof, expected - are the same as set out in the user guide url below                                              
    # https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.chi2_contingency.html

print(f"chi2 statistic:     {chi2:.5g}")
print(f"p-value:            {p:.5g}")
print(f"degrees of freedom: {dof}")
print("expected frequencies:")
print(expected)

"""
The .g used in the print formating stands for General format. 
General format: For a given precision p >= 1, this rounds the number to p significant digits and 
then formats the result in either fixed-point format or in scientific notation, depending on its magnitude."""


chi2 statistic:     24.571
p-value:            0.00040984
degrees of freedom: 6
expected frequencies:
[[ 80.53846154  80.53846154 107.38461538  80.53846154]
 [ 34.84615385  34.84615385  46.46153846  34.84615385]
 [ 34.61538462  34.61538462  46.15384615  34.61538462]]


'\nThe .g used in the print formating stands for General format. \nGeneral format: For a given precision p >= 1, this rounds the number to p significant digits and \nthen formats the result in either fixed-point format or in scientific notation, depending on its magnitude.'

In [3]:
import numpy as np
from scipy.stats import chi2_contingency


table = np.array([[90, 60, 104, 95],
                  [30, 50,  51, 20],
                  [30, 40,  45, 35]])

chi2, p, dof, expected = chi2_contingency(table)

print(f"chi2 statistic:     {chi2:.5g}")
print(f"p-value:            {p:.5g}")
print(f"degrees of freedom: {dof}")
print("expected frequencies:")
print(expected)

chi2 statistic:     24.571
p-value:            0.00040984
degrees of freedom: 6
expected frequencies:
[[ 80.53846154  80.53846154 107.38461538  80.53846154]
 [ 34.84615385  34.84615385  46.46153846  34.84615385]
 [ 34.61538462  34.61538462  46.15384615  34.61538462]]


In [4]:
import numpy as np
import scipy.stats


table = np.array([[90, 60, 104, 95],
                  [30, 50,  51, 20],
                  [30, 40,  45, 35]])

chi2, p, dof, expected = scipy.stats.chi2_contingency(table)

print(f"chi2 statistic:     {chi2:.5g}")
print(f"p-value:            {p:.5g}")
print(f"degrees of freedom: {dof}")
print("expected frequencies:")
print(expected)

chi2 statistic:     24.571
p-value:            0.00040984
degrees of freedom: 6
expected frequencies:
[[ 80.53846154  80.53846154 107.38461538  80.53846154]
 [ 34.84615385  34.84615385  46.46153846  34.84615385]
 [ 34.61538462  34.61538462  46.15384615  34.61538462]]


# Task 3 - CALCULATING STANDARD DEVIATION

November 16th, 2020: The standard deviation of an array of numbers x is calculated using numpy as np.sqrt(np.sum((x - np.mean(x))**2)/len(x)). However, Microsoft Excel has two different versions of the standard deviation calculation, STDEV.P and STDEV.S . 

The STDEV.P function performs the above calculation but in the STDEV.S calculation the division is by len(x)-1 rather
than len(x) . 

Research these Excel functions, writing a note in a Markdown cell about the difference between them. 

Then use numpy to perform a simulation demonstrating that the STDEV.S calculation is a better estimate for the standard deviation of a population when performed on a sample. Note that part of this task is to figure out the terminology in the previous sentence.

# Why NumPy is better than Excel

![OriginalComparison.png](OriginalComparison.png)

### use numpy to perform a simulation demonstrating that the STDEV.S calculation is a better estimate for the standard deviation of a population when performed on a sample. 

After much research, I felt that the easiest way to show the reader the difference between how Standard Deviation is done with NumPy compared to how it is done with Excel, was to show a side by side comparison of the formulas and the results.

When you compare NumPy np.std(GROUP_X, ddof=1) to Excel =STDEV.S(C10:G10), NumPy gives accuracy to more decimal places.<br>
On the group of numbers in GROUP_X NumPy np.std(GROUP_X, ddof=1) gives the answer: 79.05694150420949<br>
On the group of numbers in GROUP_X Excel =STDEV.S(B10:F10) gives the answer:       79.0569415<br>

If you are look at the screenshot below, if you were to try and set Excel to show 14 decimal places, Excel would round up the 79.05694150420949 to 79.05694150420950, therefore proving NumPy is more precise.

![ExcelRoundsUp.png](ExcelRoundsUp.png)

**This concludes my observations for answering Task 3. My research notes for Task 3 can be found below.**

## WHAT IS THE PURPOSE OF STANDARD DEVIATION IN RESEARCH?

>Standard Deviation (often abbreviated as "Std Dev" or "SD") provides an indication of how far the individual responses to a question vary or "deviate" from the mean. SD tells the researcher how spread out the responses are -- are they concentrated around the mean, or scattered far & wide?
https://www.greenbook.org/marketing-research/how-to-interpret-standard-deviation-and-standard-error-in-survey-research-03377


## WHAT ARE THE USES OF STANDARD DEVIATION?

> Standard deviation is a number used to tell how measurements for a group are spread out from the average (mean or expected value). A low standard deviation means that most of the numbers are close to the average, while a high standard deviation means that the numbers are more spread out.


https://simple.wikipedia.org/wiki/Standard_deviation

**Sometimes averages tell us very little about a group of numbers e.g. the average annual salary, some people are on minimum weekly wage, others are on fat cat salaries. The average annual salary often looks reasonable, however many live in extreme poverty while others are obscenely rich.**

**Look at the three group of numbers below, they all total 1000, they all average 200**
![Averages.png](Averages.png)

**The standard deviation formulas found in excel and in python modules such as NumPy help bring more meaning to analysing the numbers.**
![ExcelDeviations.png](ExcelDeviations.png)


### CALCULATING STANDARD DEVIATION FOR ENTIRE POPULATION DATA OR SAMPLE DATA?

To calculate the standard deviation of a group of numbers, the clue to how to use STDEV.P or STDEV.S is in the suffix. 


**STDEV. P** FOR AN ENTIRE POPULATION
> Work out the Mean (the simple average of the numbers)<br>
Then for each number: subtract the Mean and square the result.<br>
Then work out the mean of those squared differences.<br>
Take the square root of that and we are done!<br>
>https://www.mathsisfun.com/data/standard-deviation-formulas.html


**STDEV. S** FOR A SAMPLE POPULATION - KNOWN AS STDEV.S
>Sometimes our data is only a sample of the whole population.
>We can still estimate the Standard Deviation.
>But when we use the sample as an estimate of the whole population, the Standard Deviation formula changes to this:
>The formula for Sample Standard Deviation:
>![standard-deviation-sample.gif](standard-deviation-sample.gif)
>The important change is "N-1" instead of "N" (which is called "Bessel's correction").<BR>
>https://www.mathsisfun.com/data/standard-deviation-formulas.html



## CALCULATING STDEV.P AND STDEV.S MANUALLY WITH PYTHON / NUMPY

The formulas below show how you would do the above calculations with Python.

In [5]:
import numpy as np

# To calculate the standard deviation of an entire population e.g. STDEV.P
x = [100,200,300,150,250]
STDEVP = np.sqrt(np.sum((x - np.mean(x))**2)/len(x))
print("STDEV.P:",STDEVP)

# To calculate the standard deviation of a sample population e.g. STDEV.P
x = [100,200,300,150,250]
STDEVS = np.sqrt(np.sum((x - np.mean(x))**2)/len(x)-1)

print("STDEV.S:",STDEVS)

STDEV.P: 70.71067811865476
STDEV.S: 70.70360669725413


## CALCULATING STDEV.P AND STDEV.S EASILY WITH THE NUMPY MODULE OF PYTHON

However the above involve remembering some math and, the NumPy module of Python provides a shorthand way of doing the same calculation and getting the same result. 

https://numpy.org/doc/stable/reference/generated/numpy.std.html

We will be comparing the difference between NumPy and Excel.

In [6]:
import numpy as np
x = [100,200,300,150,250]

npstd = np.std(x, dtype=np.float64)

print(npstd)
print('Note when comparing the results above how NumPy np.std is basically the same as STDEV.P, this can be confusing because Excel STDEV is the same as STDEV.S')

70.71067811865476
Note when comparing the results above how NumPy np.std is basically the same as STDEV.P, this can be confusing because Excel STDEV is the same as STDEV.S


The STDEV. S function calculates the standard deviation in a sample set of data. Standard deviation is a measure of how much variance there is in a set of numbers compared to the average (mean) of the numbers. The STDEV. S function is meant to estimate standard deviation in a sample.

#https://stackoverflow.com/questions/34133939/is-there-any-difference-between-numpy-std-and-excel-stdev-function

There's a difference: Excel's STDEV calculates the sample standard deviation, while NumPy's std calculates the population standard deviation by default (it is behaving like Excel's STDEVP).

## To make NumPy's std function behave like Excel's STDEV, pass in the value ddof=1:

In [7]:
import numpy as np
group_x = [100,200,300,150,250]
group_y = [200,200,200,200,200]
group_z = [10,10,10,10,960]

a = np.std(group_x, ddof=1)
b = np.std(group_y, ddof=1)
c = np.std(group_z, ddof=1)


print(a)
print(b)
print(c)

#The Excel STDEV function returns the standard deviation for data that represents a sample. To calculate the standard deviation for an entire population, use STDEVP or STDEV. P.
#https://exceljet.net/excel-functions/excel-stdev-function

79.05694150420949
0.0
424.85291572496004


## Research these Excel functions, writing a note in a Markdown cell about the difference between them. 

SAMPLE
=STDEV.S(600,470,170,430,300)


POPULATION
np.std()
147.32277488562318



### STANDARD DEVIATION PERFORMED ON A POPULATION

## STDEV.P USED IN EXCEL
![STDEVP.png](STDEVP.png)
=STDEV.P(600,470,170,430,300)<br>
=STDEV.P(A3,B3,C3,D3,E3)<br>

RESULT<br>
147.3227749

## How To Do Standard Deviation In NumPy (equivalent to excel STDEV.P)

In [8]:
import numpy as np

a = np.array([100,200,300,150,250])
np.std(a)

70.71067811865476

### STANDARD DEVIATION PERFORMED ON A SAMPLE

## STDEV.S USED IN EXCEL
![STDEVS.png](STDEVS.png)
=STDEV.S(600,470,170,430,300)<br>
=STDEV.S(A3,B3,C3,D3,E3)

RESULT<br>
164.7118696

## STDEV USED IN EXCEL
![STDEV.png](STDEV.png)
=STDEV(600,470,170,430,300)<br>
=STDEV(A3,B3,C3,D3,E3)

RESULT<br>
164.7118696

## How To Do Standard Deviation In NumPy (equivalent to excel STDEV.S)

In [9]:
import numpy as np
s = [600,470,170,430,300]

np.std(s, ddof=1)


164.7118696390761

#https://numpy.org/doc/stable/reference/generated/numpy.std.html
Computing the standard deviation in float64 is more accurate:

>>>
np.std(a, dtype=np.float64)
0.44999999925494177 # may vary

In [10]:
import numpy as np
s = [600,470,170,430,300]

np.std(s, ddof=1, dtype=np.float64)

164.7118696390761

# Task 4
## Use scikit-learn to apply k-means clustering to Fisher’s famous Iris data set.

4. November 30th, 2020: Use scikit-learn to apply k-means clustering to Fisher’s famous Iris data set. You will easily obtain a copy of the data set online. Explain in a Markdown cell how your code works and how accurate it might be, and then explain how your model could be used to make predictions of species of iris.

## KMEANS HAS AN OVERALL ACCURACY OF 89.34% ANALYSING THE IRIS DATASET

To understand how to apply k-means clustering to Fisher’s famous Iris data set I watched the video https://www.youtube.com/watch?v=asW8tp1qiFQ, while watching the video I typed the code and added the narration comments and my own print statements to explain the code.

I found this video particularly helpful for showing how accurate kmeans is, because it ends with a piece of code from pandas that shows a crosstab kmeans classification.

In the Iris dataset, there are 150 Iris flowers, 50 of each of the three species, a 100% correct classification should show 50 under each tab (e.g. 0,1,2)

![kmeanstable.png](kmeanstable.png)

kmeans was able to show 50 under tab 2, one may assume that species 2 was easy to classify for kmeans, and that it did it with 100% accuracy, this would require further investigation.

kmeans shows 2 missclasifications for 1, and 14 misclassifcations for 0

that is 16 misclassifications out of 150 = 10.66% of the data, which mean **kmeans has an overall accuracy of 89.34% analysing the Iris dataset**

> import pandas as pd<br>
  pd.crosstab(iris.target,KModel.labels_)<br>
  
To get a feel for how to use kmeans to predict accuracy I also tried to use kmeans.predict on a few individual samples

> import numpy as np<br>
> newvals = np.array([[5.1, 3.5, 1.4, 0.2],[4.9, 3.,  1.4, 0.2],[4.7, 3.2, 1.3, 0.2],[4.6, 3.1, 1.5, 0.2]])<br>
> predictions = kmeans.predict(newvals)<br>
> print(predictions)<br>

However the cross tab table above gives the best insight into kmeans prediction accuracy.

In [34]:
#I watched the video https://www.youtube.com/watch?v=asW8tp1qiFQ, typed the code and added the narration comments and
#my own print statements to explain the code

from sklearn.datasets import load_iris #load inbuilt dataset from sklearn
iris = load_iris() #assign variable name iris to inbuilt dataset

iris.data # contains the four numeric variables, sepal length, sepal width, petal length, petal width

print(iris.data) #printing the measurements of the Iris Dataset below

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [12]:
iris.target # relates to the different species shown as 0,1,2 for the three different   
            # species of Iris, a categorical variable, basically a label


print(iris.target)

print("""\nThe array above shows the three types of Iris flower. 
There are 150 Iris in the dataset, 50 of each Iris type.
all the zeros represent one Iris type,
all the ones represent another Iris type,
all the twos represent another Iris type""")

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]

The array above shows the three types of Iris flower. 
There are 150 Iris in the dataset, 50 of each Iris type.
all the zeros represent one Iris type,
all the ones represent another Iris type,
all the twos represent another Iris type


In [13]:

from sklearn.cluster import KMeans
kmeans = KMeans(n_clusters=3) #with KMeans you get to pre specify the number of Clusters


In [14]:
kmeans

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
       n_clusters=3, n_init=10, n_jobs=None, precompute_distances='auto',
       random_state=None, tol=0.0001, verbose=0)

In [15]:
KModel = kmeans.fit(iris.data) #fit a model using the training data , in this case original Iris Data passed through

In [16]:
KModel

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
       n_clusters=3, n_init=10, n_jobs=None, precompute_distances='auto',
       random_state=None, tol=0.0001, verbose=0)

In [17]:
KModel.labels_

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1], dtype=int32)

When you train the Iris Dataset

In [19]:
import pandas as pd
pd.crosstab(iris.target,KModel.labels_)

col_0   0   1   2
row_0            
0       0   0  50
1       2  48   0
2      36  14   0

In [40]:
import numpy as np

newvals = np.array([[5.1, 3.5, 1.4, 0.2],[4.9, 3.,  1.4, 0.2],[4.7, 3.2, 1.3, 0.2],[4.6, 3.1, 1.5, 0.2]])
predictions = kmeans.predict(newvals)
print(predictions)

[0 1 1 1]


------------------------------------------------------------

In [41]:
import numpy as np

newvals = np.array([[5.8, 2.7, 5.1, 1.9],[6.8, 3.2, 5.9, 2.3],[6.7, 3.3, 5.7, 2.5],[6.7, 3.,  5.2, 2.3],[6.3, 2.5, 5.,  1.9],[6.5, 3.,  5.2, 2. ],[6.2, 3.4, 5.4, 2.3],[5.9, 3.,  5.1, 1.8]])
predictions = kmeans.predict(newvals)
print(predictions)

[0 0 0 0 0 0 0 0]


Other Resources to watch for scikit-learn to apply k-means clustering to Fisher’s famous Iris data set

https://www.youtube.com/watch?v=asW8tp1qiFQ<br>
https://www.youtube.com/watch?v=nlD8A-49Fc0<br>
https://www.youtube.com/watch?v=hd1W4CyPX58<br>
https://www.youtube.com/watch?v=I38fOLHC8zo<br>
https://www.youtube.com/watch?v=iMJZAWdQx7g<br>
https://www.youtube.com/watch?v=K1quNyRP86Q<br>
https://www.youtube.com/watch?v=VjPmHQyONYI<br>
https://github.com/palak2323/The-Spark-Foundation-internship-/blob/main/IRIS(KMEANS_CLUSTERING).ipynb<br>
https://gist.github.com/bbarrilleaux/9841297<br>
https://www.kaggle.com/tonzowonzo/simple-k-means-clustering-on-the-iris-dataset<br>
https://scikit-learn.org/stable/modules/generated/sklearn.cluster.KMeans.html#sklearn.cluster.KMeans<br>